### ISSUE TITLE
Meeting Notes 3/28/2017

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jblast#26]
From last two pages of presentation + additional notes
1. Refactor hook for server-side deployment – npm package (do it)
2. Refactor jblast-tools as a separate installable package. – for global deployment.
	Discussion:
	We may be able to do away with Galaxy Jblast Tools if we migrate the BlastXML to JSON operation to the Jblast side.
	Arguments: should the blast simulation tools be installed by default?
	This can simplify one of the setup step procedure.
3. Move Jblast API into JBlast Model for better adoption into policy engine
	Discussion: API refactor 
4. Add DataSet Model to complement track model - Yes
5. Finish isAdmin policy - Yes
6. User Management Page - I think this we a Yes
7. Fix bootstrap AMD loading issue - Yes
	This was not discussed, but I had the idea to introduce a template jbrowse master.  This can be used to selectively turn on features from, say index.*.  Discussion
8. Resolve Galaxy history create - trouble spot - Yes
	This was not discussed.  I had the idea to simply do away with the creation of a Jblast history and just use the default "Unnamed History".  The option will still be available in Jblast config file to choose an alternate history for tasks, but the user must manually create the history in Galaxy.
9. Implement Blast with NCBI API and BlastXML2 as Custom Workflow Engine – Refactor packaging of this to coexist with JBlast - Galaxy plugin (this will probably be done after the first release of jblast)
	Not discussed.  I had this in mind:  refactor the jblast to separate Blast management portion Galaxy workflow and create a separate workflow.  For future discussion
10. Dockerize with dependency on Galaxy Blast Docker
	Discussion: 
	We should move this to higher priority, given the numerous steps involved with jblast, but it should not hold up a release.
	I did a considerable amount of work with docker.
11. Refactor JBserver to be installed in JBrowse directory as npm package.
	Was not discussed
12. Bearer Auth for backend API access.
	Discussion: generally needed, not sure if it was decided to be in the first release.
13. Backbone Support
	Pie in the sky - forget it.
14. Client auto connect detection
	Not critical for first release, nice to have.
15. Remote galaxy server support
	Not critical - nice to have.
16. Re-evaluate REST APIs
	1. Concern of model exposure (User, Track, etc) full CRUD operations
	2. Make API more uniform - Blueprint Models, some non-blueprint APIs, & Kue
	3. Exposure can be managed completely through policy engine on a per method/function basis.  Can also be completely turned off for certain objects.
	4. Action: Find an easier way to document APIs through markup tags for review.  Jsdoc generates too much garbage.
	5. Action: create a Code Review for APIs
17. Installation Procedure Review
	1. Action: First do some of the install improvements, npm packaging, etc.
	2. Action: create Code Review for Install Steps
18. Tests
	1. Action: Develop API regression tests
19. Remove blast filter panel animation
20. Moving to tabbed view
	Discussion: Ian originally suggested a tabbed interface; however, what I implemented was a slide-in panel. 
	I think it was decided to keep it as is for now.
21. In the job queue panel
	"St" for "State" is a little ambiguous.

**Comment by ihh** [comment]
For the record the concerns I expressed about using Sails' [blueprints](http://sailsjs.com/documentation/reference/blueprint-api) are as follows: they confuse the documentation of a clean API by implying that CRUD operations directly reading and writing the application's underlying data model are supported. This can work in the very restricted case of apps that are essentially CRUD, but ours is not. It is true that blueprints can be partially disabled but this is not a sensible way to design an API, i.e., borrowing someone else's API intended for a different task and then disabling half of it and repurposing the rest. It leaves parts of the namespace off-limits (the disabled parts of the borrowed API), it can confuse users of the API, and it is likely to be sub-optimal for the intended purpose.

It is true that a good API should be as RESTful as possible, that is, it should use HTTP verbs (GET, POST, etc) as close as possible to their original sense and the API endpoints should refer to clearly identifiable objects, but in my experience this is rarely achieved by exposing the object-relational model over HTTP except (as noted above) in the rare case where the app is pure CRUD, meaning that _every single database row and column_ is something that sufficiently authorized users should, at some point, be able to read and write directly.

I recommend decoupling our API entirely from the blueprints API. The blueprints methods should be disabled for release, though it may be useful to enable them for debugging via tools like [Postman](https://www.getpostman.com/).

More generally, the API needs to be documented and it needs a thorough code review probably followed by a renaming. This is the single hardest to change part of the JBrowse server/JBlast after release, so we need to get it right.

**Comment by ihh** [comment]
Regarding point 8, I support having JBlast use Galaxy's default unnamed history by default, and indeed as a general policy I support anything that simplifies the install process, e.g. migrating BlastXML->JSON from Galaxy to JBLAST (if this does indeed simplify the install).

**Comment by ihh** [comment]
Regarding point 4: the point I was trying to make in our meeting is that users should have a clear understanding and expectation about what responsibilities JBServer is assuming when it's installed. The simplest and most natural interpretation would be that JBServer assumes all responsibilities for management of JBrowse JSON files, and that the JBrowse loader scripts would *all* be made available via API endpoints. If possible these API endpoints could be RESTful, although this might not be entirely possible in the first iteration.

We need to review the API as it currently stands so we can see how to get to that point. Datasets (i.e. supporting multiple genomes, each with its own isolated annotation space, set of reference sequences, etc) are a natural part of that, but I think we should review the existing API first.

**Comment by ihh** [comment]
Re points 19 and 20. The issue I have with the BLAST filter panel is that it moves the track list out of its usual spot. I proposed tabs as a solution to this. I do not think the animation is a solution so much as a workaround (it assumes that moving the track list is a given, and instead tries to draw the user's eye to this with an animation, which however is not aligned with the direction in which the panel is "coming from" and furthermore is not visually consistent - and therefore jars - with other JBrowse animations, e.g. the one that hides the track list or the panning & zooming animations). Furthermore, the animation appears to have taken more effort than it would have required to introduce tabs, and is nevertheless not finished. That is why I recommend abandoning this part of the UI for now but if any more effort is put into this I would like it to be in implementing a simple tabbed view.

**Comment by ihh** [comment]
Re point 18. Yes, tests are essential; it's hard to believe we've gotten this far without them. I recommend using Mocha, which is [well integrated](http://sailsjs.com/documentation/concepts/testing) with Sails, to test the controllers. I've found testing the sockets to be a little harder, and perhaps the easiest way is to just skip unit tests for the sockets and go straight to integration tests with Selenium.

**Comment by enuggetry** [comment]
22. Accession stragegy is a configurable option.

**Comment by enuggetry** [comment]
Regarding 16 - API:

I think it would be better to leverage blueprint models and contain the exposure of routes via the policy framework, while establishing consistent model/class naming.
- blueprints provides a convenient way to extend the model methods, which have automatic "action" routes whose exposure can be managed by policy.
- the built-in "find" is pretty robust to give up (http://sailsjs.com/documentation/reference/blueprint-api/find-where)
- It's pretty much already there, with exception of queue model. (it's a matter of applying policies.
- model methods can be extended and there will be a natural action
- And we wouldn't have to maintain a set of routes that is essentially translating to internal models.

To establish consistency we might rename the models and routes:
/jbuser
/jbtrack
/jbdataset
/jbqueue
/jbglobal
/jblast (jblast specific api)

Sails policies and routes.
http://sailsjs.com/documentation/concepts/policies

Action Routes and Blueprints
http://sailsjs.com/documentation/concepts/blueprints/blueprint-routes
http://sailsjs.com/documentation/reference/blueprint-api

**Comment by enuggetry** [comment]
re: ihh comments on #4.
While JBserver to some extent "manages" the trackList.json.  It does not preclude using perl tools or hand modifying the config.  Indeed, if the configs are changed externally, JBserver monitors and absorbs the changes.   My intent here was to take advantage of mechanism to notify clients automatically of changes, allowing them to dynamically update as necessary (a nice feature of having a server).  However, client-side response is not fully fleshed out.  Eventually, the function would go into the JBclient plugin.

**Comment by ihh** [comment]
Sails is open source: the `find` method is easy to extract & duplicate. We do not have semantically meaningful DELETE, POST, PUT, for every model. Nor do we (presumably) expect the client to be able to write (or read) every attribute of every model. It is cleaner to define a new set of routes than to have a partial overlap. "Maintaining a set of routes that translate to internal models" is the entire point of designing a REST API!

Again: we are not a CRUD application. JBrowse server is not a thin layer on top of a database with inert fields which are trivially transformed by the view. I do not see the rationale for defining the API for a queue-based application by starting with a RESTful API derived from a database model and then deleting methods. Queues and CRUD stores are very different things.

Sails policies can be applied to non-blueprint actions too.

**Comment by ihh** [comment]
Regarding point 4 (you probably don't want to use hash characters in these comments as they auto-link to other issues. One could argue that the original list of 21 points might be better separated into individual issues but that's a bit beside the point...)

The point here is to have a clear, concise definition of what JBServer does. If it is a daemon that monitors the config files and notifies the client when they change, OK. If it takes over responsibility for managing the config files, either completely or in a specifically narrowly-defined way, that's fine too. But it needs to be clearly articulated what it is doing otherwise it is just a bundle of confusion...

**Comment by enuggetry** [comment]
Well, that's my point, it doesn't have to expose the CRUD interfaces, while housing other methods/routes in a blueprints naturally consistent method of exposure.  Meanwhile, the CRUD can be enabled for debugging, if necessary.  The API model not inconsistent with, say Galaxy.

**Comment by enuggetry** [comment]
I had some problems applying policies to a custom route.  But, admittedly, I didn't spend much time debugging it.

**Comment by ihh** [comment]
It is fine to use the blueprint API for debugging but it is cleaner to disable/enable the entire blueprint API (with the understanding that it would all be disabled in production) than to have some subset of it disabled but temporarily enabled for the purposes of debugging, which is an inherently flaky situation, and harder to keep track of.

Consistency is fine and good but let's avoid sloppy overlaps between our API and blueprints please. If you want to leverage the blueprint code for `find`, then why not simply copy it into a new method. The [code for the blueprint actions is all available and easy to borrow from](https://github.com/balderdashy/sails/tree/master/lib/hooks/blueprints/actions).

Perhaps I do not understand enough about Galaxy to find your reference to their API model to be persuasive - are you saying that the Galaxy API is derived from a REST API that was automatically generated by an MVC framework like Sails?

**Comment by ihh** [comment]
My experience is that policies work fine with regular controller actions....

I really do not want to keep arguing this by github issues, I thought we had discussed this at length yesterday but I have many, many reasons to dislike blueprints. I think they are a false economy that short-circuits the real work of designing a sensible API. Here is another example of why:

It would be natural for us to have a route like `/job/new` (for example) but this would mean something entirely different from the Sails blueprint with the same name. Adding a job is not just poking a new entry into the database, it involves a whole load of other stuff. So we will find ourselves (a) redefining `new` to mean something different, or (b) avoiding `new`, or using a different action name. Either way we have compromised our API design for the dubious benefit of leveraging Sails-generated code and routes.

There are many other such reasons. If we must argue about this then let's do so in person.

**Comment by enuggetry** [comment]
The point is to leverage blueprints for mapping methods to routes.  The solution to /job/new is to either overload the original method or create a new method.

**Comment by ihh** [comment]
Mapping methods to routes is as easy as adding a line to `config/routes.js`

This is a lot easier in the long run than importing the entire training-wheels apparatus of blueprints and selectively deleting parts of it

**Comment by ihh** [comment]
Or rewriting, overloading, etc

**Comment by nathandunn** [comment]
Sorry for the delay (was a bit distracted last time):

- is there a reason to prefix routes with "jb"?   I agree with most of the points [here](https://github.com/GMOD/jblast/issues/26#issuecomment-290256314), otherwise. 
- I agree with blueprints.  Nice to start out, but Grails uses something similar (creates controllers for all operations).   Very handy for some admin screens to add properties, but otherwise cruft.   I don't see a problem with including it initially, though.
- don't abbreviate words if possible (21, and the API)
- I think that docker is a must.  Docker compose is nice for development, but whatever seems easiest.   Including it with Galaxy I think would be good.
- npm build is good
- hooks are good

I agree that backbone support isn't essentials.  Not sure why we would need another auth package if we have passport.  Same with client auto connect and remote galaxy server support. 

Good directions all around.

**Comment by enuggetry** [comment]
closing this.
Have moved individual items to their own issues, as well as separate jbserver vs jblast items.
